spring:
  profiles:
    active: local
  thymeleaf:
    prefix : classpath:templates/
    suffix : .html
    cache : false
  config:
    import: oauth2.yml,apiKey.yml,database.yml

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

      
springdoc:
  version: '0.1'
  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  show-actuator: true

logging:
  level:
    com.nadeul: DEBUG
    
---
spring:
  config:
    activate:
      on-profile: local
  devtools:
    restart:
      enabled: true
      
server:
  title: nadeul-local
  port : 8082
  
---
spring:
  config:
    activate:
      on-profile: prod
  devtools:
    restart:
      enabled: true

server:
  title: nadeul-prod
  port : 8083

 