spring:
  profiles:
    active: local
  thymeleaf:
    prefix : classpath:templates/
    suffix : .html
    cache : false
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
        
---
spring:
  config:
    activate:
      on-profile: local
  devtools:
    restart:
      enabled: true
server:
  title: nadeul-local
  port : 8080
  
---
spring:
  config:
    activate:
      on-profile: prod
  devtools:
    restart:
      enabled: true

server:
  title: nadeul-prod
  port : 8081

 